export { default as Navbar } from './Navbar/Navbar'
export { default as Categories } from './Categories/Categories'
export { default as Explore } from './Explore/Explore'
export { default as Footer } from './Footer/Footer'
export { default as Quality } from './Quality/Quality'
export { default as Review } from './Review/Review'
export { default as Offer } from './Offer/Offer'
export { default as Cover } from './Cover/Cover'
export { default as About } from './About/About'
export { default as Auth } from './Auth/Auth'

