export { default as Home } from './Home/Home'
export { default as Repair } from './Repair/Repair'
export { default as Kitchen } from './Kitchen/Kitchen'
export { default as Bedroom } from './Bedroom/Bedroom'
export { default as Livingroom } from './Livingroom/Livingroom'
export { default as Profile } from './Profile/Profile'
export { default as Cart } from './Cart/Cart'